/** Riyadh districts & neighborhoods — bilingual labels for the lead form. */
export const RIYADH_AREAS = [
  { id: "olaya", label: { ar: "العليا", en: "Al Olaya" } },
  { id: "sulaimaniyah", label: { ar: "السليمانية", en: "Al Sulaimaniyah" } },
  { id: "sahafa", label: { ar: "الصحافة", en: "Al Sahafah" } },
  { id: "yasmin", label: { ar: "الياسمين", en: "Al Yasmin" } },
  { id: "narjis", label: { ar: "النرجس", en: "Al Narjis" } },
  { id: "malqa", label: { ar: "الملقا", en: "Al Malqa" } },
  { id: "nakheel", label: { ar: "النخيل", en: "Al Nakheel" } },
  { id: "hittin", label: { ar: "حطين", en: "Hittin" } },
  { id: "qirawan", label: { ar: "القيروان", en: "Al Qirawan" } },
  { id: "arid", label: { ar: "العارض", en: "Al Arid" } },
  { id: "hamra", label: { ar: "الحمراء", en: "Al Hamra" } },
  { id: "wurud", label: { ar: "الورود", en: "Al Wurud" } },
  { id: "rabwah", label: { ar: "الربوة", en: "Al Rabwah" } },
  { id: "mohammadiyah", label: { ar: "المحمدية", en: "Al Mohammadiyah" } },
  { id: "faisaliyah", label: { ar: "الفيصلية", en: "Al Faisaliyah" } },
  { id: "murooj", label: { ar: "المروج", en: "Al Murooj" } },
  { id: "granada", label: { ar: "غرناطة", en: "Granada" } },
  { id: "rawdah", label: { ar: "الروضة", en: "Al Rawdah" } },
  { id: "malaz", label: { ar: "الملز", en: "Al Malaz" } },
  { id: "naseem", label: { ar: "النسيم", en: "Al Naseem" } },
  { id: "shifa", label: { ar: "الشفا", en: "Al Shifa" } },
  { id: "aziziyah", label: { ar: "العزيزية", en: "Al Aziziyah" } },
  { id: "manar", label: { ar: "المنار", en: "Al Manar" } },
  { id: "king-fahd", label: { ar: "حي الملك فهد", en: "King Fahd District" } },
  { id: "king-abdullah", label: { ar: "حي الملك عبدالله", en: "King Abdullah District" } },
  { id: "diplomatic", label: { ar: "الحي الدبلوماسي", en: "Diplomatic Quarter" } },
  { id: "ghadir", label: { ar: "الغدير", en: "Al Ghadir" } },
  { id: "aqiq", label: { ar: "العقيق", en: "Al Aqiq" } },
  { id: "murabba", label: { ar: "المربع", en: "Al Murabba" } },
  { id: "dirah", label: { ar: "الديرة", en: "Al Dirah" } },
  { id: "batha", label: { ar: "البطحاء", en: "Al Batha" } },
  { id: "deira", label: { ar: "ديرة", en: "Deira" } },
  { id: "laban", label: { ar: "لبن", en: "Laban" } },
  { id: "tuwaiq", label: { ar: "طويق", en: "Tuwaiq" } },
  { id: "dharat-laban", label: { ar: "ظهرة لبن", en: "Dharat Laban" } },
  { id: "ishbiliyah", label: { ar: "إشبيلية", en: "Ishbiliyah" } },
  { id: "rimayah", label: { ar: "الريماية", en: "Al Rimayah" } },
  { id: "masif", label: { ar: "المصيف", en: "Al Masif" } },
  { id: "nadhim", label: { ar: "النظيم", en: "Al Nadheem" } },
  { id: "khaleej", label: { ar: "الخليج", en: "Al Khaleej" } },
  { id: "suwaidi", label: { ar: "السويدي", en: "Al Suwaidi" } },
  { id: "shubra", label: { ar: "شبرا", en: "Shubra" } },
  { id: "jaradiyah", label: { ar: "الجرادية", en: "Al Jaradiyah" } },
  { id: "mansourah", label: { ar: "المنصورة", en: "Al Mansourah" } },
  { id: "other", label: { ar: "حي آخر في الرياض", en: "Other area in Riyadh" } },
] as const;
